#!/bin/bash

build_package() {
    python -m build src
}

install_package() {
    poetry add ./src/dist/*.whl
}


init_git_and_commit() {
    git init
    git branch -M main
    git add . 
    git commit -m "First cutter project commit"
}


test:all() {
    poetry run python -m pytest -n auto
}

test:stop-at-first-fail() {
    poetry run python -m pytest -x -n auto
}

test:last-fail() {
    poetry run python -m pytest -lf -n auto
}

lint() {
    git add .; SKIP=no-commit-to-branch pre-commit run --all-files --show-diff-on-failure
}

help() {
    echo "${1} <task> <arg>"
    echo "Tasks:"
    compgen -A function | cat -n 
}


TIMEFORMAT="Task complete in %3lR"
time ${@:-help}
