#!/bin/bash

build_package() {
    python -m build src
}

install_package() {
    poetry add ./src/dist/*.whl
}




test:all() {
    poetry run python -m pytest -n auto
}

test:stop-at-first-fail() {
    poetry run python -m pytest -x -n auto
}

test:last-fail() {
    poetry run python -m pytest -lf -n auto
}

lint() {
    git add .; SKIP=no-commit-to-branch pre-commit run --all-files --show-diff-on-failure
}

# For local usage
create-project-workflow() {

    repo-setup
    second-commit-to-feat-branch-and-make-pr

}

repo-setup() {
    create-repo-if-not-exists
    generate-cutter-project
    make-first-commit-to-main
}


# args:
#   - GIHUB_USERNAME
#   - REPO_NAME
#   - IS_PUBLIC 
create-repo-if-not-exists() {
    local is_public=${IS_PUBLIC:-false}

    echo "Checking is repo existing..."

    # only when previous code succeeds the code after && will get executed
    gh repo view "${GITHUB_USERNAME}/${REPO_NAME}" > /dev/null \
    && echo "Repo exists, exiting..." && return 0 

    echo "Repo does not exist, creating...."

    if [[ "$is_public" == "true"  ]]; then
        PUBLIC_OR_PRIVATE="public"
    else
        PUBLIC_OR_PRIVATE="private"
    fi 

    gh repo create "${GITHUB_USERNAME}/${REPO_NAME}" "--${PUBLIC_OR_PRIVATE}"
}



generate-cutter-project() {

    local output_dir="./${REPO_NAME}"

    CONFIG_FILE_PATH="./${REPO_NAME}.config.yaml"
    cat <<EOF > ${CONFIG_FILE_PATH}
default_context:
    repo_name: ${REPO_NAME}
    example_pkg: ${PACKAGE_NAME}
EOF

    cookiecutter ./ \
        --no-input \
        --config-file ${CONFIG_FILE_PATH}

    rm ${CONFIG_FILE_PATH}

}


make-first-commit-to-main() {
    set -x
    cd "${REPO_NAME}"
    git init
    git branch -M main

    set-git-config


    git add . 
    git commit -m "initial commit"
    git push origin main
    echo "cool"
}

set-git-config() {
    git config --global user.name "${GITHUB_USERNAME}"
    git config --global user.email "test@test.mail"
    git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_USERNAME}/${REPO_NAME}.git
}



delete-project-dir() {
    cd -
    rm -rf ${REPO_NAME}
}


second-commit-to-feat-branch-and-make-pr() {
    git clone "https://github.com/${GITHUB_USERNAME}/${REPO_NAME}.git"
    cd ${REPO_NAME}

    set-git-config

    lint-and-commit-to-feat-branch
    open-pr-from-feat-to-main
}



lint-and-commit-to-feat-branch() {
    set -x
    git checkout -b feat/pupulate-project-from-template
    touch makeing-pr.txt
    lint 
    git add . # Assume pre-commit autofix modified files
    git commit -m "feat/populated from template project."
    git push -u origin feat/pupulate-project-from-template
}

open-pr-from-feat-to-main() {
    gh pr create \
        --title "feat/populated from template project." \
        --body "Merge generated project from feat to main." \
        --base main \
        --head feat/pupulate-project-from-template \
        --repo "${GITHUB_USERNAME}/${REPO_NAME}"
}



configure-repo() {
    # configure secret
    set-repo-variables
    # protect main branch, forcing passing build on feature branch
    configure-branch-protection-using-gh-api
}


set-repo-variables() {
    gh variable set YONKO -b "Kaido" --repo "${GITHUB_USERNAME}/${REPO_NAME}"
    gh variable set PirateKing -b "Roger" --repo "${GITHUB_USERNAME}/${REPO_NAME}"
}


configure-branch-protection-using-gh-api() {
    local BRANCH="main"
    gh api \
        --method PUT \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/${GITHUB_USERNAME}/${REPO_NAME}/branches/${BRANCH}/protection" \
        -F "required_status_checks[strict]=true" \
        -F "required_status_checks[checks][][context]=test" \
        -F "required_status_checks[checks][][context]=lint" \
        -F "enforce_admins=null" \
        -F "restrictions=null" \
        -F "required_pull_request_reviews[required_approving_review_count]=1" \
        > /dev/null
}


run-create-orupdate-repo() {
    git add .
    git commit -m "fix:debugging the create-or-update-repo.yml"
    git push origin main

    gh workflow run .github/workflows/create-or-update-repo.yml \
        -f repo_name="pirate" \
        -f is_public_repo=true  \
        -f package_import_name="yonko" \
        --ref main 
}


help() {
    echo "${1} <task> <arg>"
    echo "Tasks:"
    compgen -A function | cat -n 
}


TIMEFORMAT="Task complete in %3lR"
time ${@:-help}
