name: Create or Update repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the repo to create"
        required: true
        type: string

      is_public_repo:
        description:  "If unchecked, the repo is private"
        required: true
        default: false
        type: boolean

      package_import_name:
        description: "Your package name you want to build in the project"
        required: true
        type: string

env:
  GH_TOKEN: ${{ secrets.PERSRONA_TOKEN }}
  GITHUB_USERNAME: wrbyepct
  REPO_NAME: ${{ github.event.inputs.repo_name }}


permissions:
  contents: write

jobs:
  
  create-repo-if-not-exists:
    runs-on: ubuntu-latest

    env:
      IS_PUBLIC: ${{ github.event.inputs.is_public_repo }}
      PACKAGE_NAME: ${{ github.event.inputs.package_import_name }}

 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with: 
          python-version: 3.12
      

      - name: Install dependencies
        run: |
          pip install cookiecutter pre-commit
          
      - name: Create Repo If Not Exists
        run: | 
          bash -x run repo-setup
          

  open-pull-request-to-feature-to-branch:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with: 
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          pip install pre-commit

      - name: Generate CookieCutter Project
        run: |
          bash -x run second-commit-to-feat-branch-and-make-pr



  configure-repo:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Main Branch Protection & Passing Build Rules
        run: |
          bash -x run configure-repo

 